const types = {
  SET_KEYWORD_INPUT: "SET_KEYWORD_INPUT",
  GET_KEYWORD: "GET_KEYWORD",
  SET_KEYWORD: "SET_KEYWORD",
  GET_INGREDIENT: "GET_INGREDIENT",
  ADD_INGREDIENT: "ADD_INGREDIENT",
  REMOVE_INGREDIENT: "REMOVE_INGREDIENT",
  ALL_INGREDIENTS: "ALL_INGREDIENTS",
  SET_ERROR: "SET_ERROR",
  SET_NO_RECIPES_FOUND: "SET_NO_RECIPES_FOUND",
  GET_ALL_RECIPES: "GET_ALL_RECIPES",
  SET_RECIPES: "SET_RECIPES",
};
export default types;
